In [154]:
import numpy as np
import datetime as dt 
import csv
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

## Pre-Processing
Reading in csv files and setting up Dataframes.

In [155]:
year = 2025
regular_rider_cutoff = 4

# Read and set up data
rides_df = pd.read_csv(f'tbd_stats_{year}.csv')
att = pd.read_csv(f"sat_attendance_{year}.csv")
rider_cols = att.columns[1:]
attendance_df = att.melt(
    id_vars=["date"],
    value_vars=rider_cols,
    var_name="slot",
    value_name="rider"
)
# Set up DFs
attendance_df = attendance_df.dropna(subset=["rider"])
attendance_df = attendance_df[attendance_df["rider"].str.strip() != ""]
attendance_df["rider"] = attendance_df["rider"].str.strip()
attendance_df = attendance_df.drop(columns=["slot"])
# Normalize Dates
rides_df["date"] = pd.to_datetime(rides_df["date"]).dt.normalize()
attendance_df["date"] = pd.to_datetime(attendance_df["date"]).dt.normalize()

/var/folders/6s/2lcz4zcx0515kv6t7ks2qj0h0000gn/T/ipykernel_2233/3472303849.py:20: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

/var/folders/6s/2lcz4zcx0515kv6t7ks2qj0h0000gn/T/ipykernel_2233/3472303849.py:21: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

In [156]:
attendance_df

          date  rider
0   2025-01-04   Anna
1   2025-01-18   Anna
2   2025-02-01   Anna
3   2025-02-15   Anna
4   2025-02-22   Anna
..         ...    ...
883 2025-08-16   unk4
921 2025-06-28  Wenbo
925 2025-07-26  Wenbo
928 2025-08-16   unk5
973 2025-08-16   unk6

[498 rows x 2 columns]

In [157]:
rides_df

,date,official_ride,start,route,full_route,coffee_shop,num_riders,miles,selfie
0,2025-01-04,True,CCT Trailhead,WOD,MVT-WOD,Rare Bird,10,18,True
1,2025-01-18,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,8,20,True
2,2025-02-01,True,CCT Trailhead,CCT-RCP,CCT-RCP,Olivia's Kitchen,14,20,True
3,2025-02-15,True,Gravelley Point,Alexandria,MVT-Crystal City,Swing's,6,19,True
4,2025-02-22,True,Navy Yard,ART-MBT,ART-MBT,Vigilante,8,16,True
5,2025-03-01,True,Gravelley Point,WOD,MVT-WOD,Rare Bird,8,18,True
6,2025-03-08,True,Gravelley Point,Alexandria,MVT-Crystal City,Hypergoat,9,16,True
7,2025-03-15,True,Navy Yard,ART-MBT,ART-MBT,Vigilante,14,19,True
8,2025-03-22,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,12,20,True
9,2025-03-29,True,Gateway Park,WOD,Military-WOD,Coffee Republic,14,28,True
10,2025-04-05,True,Gravelley Point,Alexandria,MVT-Crystal City,Misha's,10,17,True
11,2025-04-12,True,Gateway Park,WOD,MVT-WOD,Frames,10,33,True
12,2025-04-19,True,Navy Yard,ART-MBT,ART-MBT,Vigilante,10,16,True
13,2025-04-25,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,10,20,True
14,2025-05-03,True,Gravelley Point,Alexandria,MVT-Crystal City,Swing's,8,19,True
15,2025-05-10,True,Gateway Park,WOD,Military-WOD-MVT,Rare Bird,9,25,True
16,2025-05-17,True,Navy Yard,ART-MBT,ART-MBT,Mt Rainier Farmers Market,11,16,True
17,2025-05-24,True,Gravelley Point,WOD,MVT-WOD,Monk's,13,97,True
18,2025-05-31,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,10,20,True
19,2025-06-07,True,Navy Yard,Alexandria,Oxon Hill-Crystal City,Misha's,14,18,True
20,2025-06-21,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,7,20,True
21,2025-06-28,True,Dupont Circle,RCP-MBT,RCP-MBT,Donut Run,21,16,True
22,2025-07-05,True,Navy Yard,ART-MBT,ART-MBT,Vigilante,8,16,True
23,2025-07-12,True,Dupont Circle,Alexandria,MVT-Crystal City,Hypergoat,19,15,True
24,2025-07-19,True,Gateway Park,WOD,Military-WOD,Frames,11,28,True
25,2025-07-26,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,21,20,True
26,2025-08-02,True,Navy Yard,ART-MBT,ART-Sligo-MBT,Vigilante,18,33,True
27,2025-08-09,False,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,2,20,True
28,2025-08-16,True,Arlington Cemetery,WOD,MVT-WOD,Rare Bird,22,20,True
29,2025-08-23,True,Gravelley Point,Alexandria,MVT-Crystal City,Swing's,16,19,True
30,2025-08-30,False,Gateway Park,WOD,MVT-WOD,Weenie Beenie,8,33,True
31,2025-09-06,True,CCT Trailhead,CCT-RCP,CCT-RCP,Bethesda Bagel,11,20,True
32,2025-09-13,True,Navy Yard,Alexandria,Oxon Hill-Crystal City,Swing's,16,18,True
33,2025-09-20,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,10,20,True
34,2025-09-27,True,Grace Street Coffee,ART-MBT,RCP-Sligo-ART,Vigilante,9,33,True
35,2025-10-04,True,Gravelley Point,Alexandria,MVT-Crystal City,Buzz Bakeshop,12,19,True
36,2025-10-11,True,Gateway Park,WOD,Military-WOD,Frames,11,28,True
37,2025-10-18,True,Gateway Park,Alexandria,MVT-Crystal City,Hypergoat,9,19,True
38,2025-10-25,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,14,20,True
39,2025-11-01,True,CCT Trailhead,CCT-RCP,CCT-RCP,Coffefi,6,20,True
40,2025-11-02,True,Gravelley Point,NOVA Loop,NOVA Loop,Myung Ga Kimbap,10,55,True
41,2025-11-08,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,11,20,True
42,2025-11-15,False,CCT Trailhead,CCT-RCP,CCT-RCP,Grace Street Coffee,5,20,True
43,2025-12-06,True,Navy Yard,Alexandria,Oxon Hill-Crystal City,St. Elmo's,6,18,True
44,2025-12-20,True,Gateway Park,Alexandria,WOD-Crystal City,Swing's,6,20,True

## DFs for Charts

Plot for top riders by attendance leaderboard (min 5 rides this year). This is plotted in both scatter plot and line graph. 
Also plots for shortest hiatus and longest streak among the regular riders.

In [158]:
attendance_counts = (
    attendance_df.groupby("rider")["date"]
    .count()
    .reset_index(name="count")
)
attendance_regular = attendance_counts[attendance_counts["count"] > regular_rider_cutoff]
attendance_regular = (
    attendance_regular.sort_values(
        by=["count", "rider"],
        ascending=[False, True]  # desc count, asc name
    ).assign(rank=lambda df: range(1, len(df) + 1))
)
regular_riders = attendance_counts[attendance_counts["count"] > regular_rider_cutoff]["rider"]

In [159]:
attendance_with_miles = attendance_df.merge(
    rides_df[['date', 'miles']],
    on='date',
    how='left'
)

attendance_with_miles = attendance_with_miles[
    attendance_with_miles['rider'].isin(regular_riders)
]
mileage_leaderboard = (
    attendance_with_miles
        .groupby('rider', as_index=False)
        .agg(total_miles=('miles', 'sum'),
             rides_attended=('date', 'count'))
        .sort_values('total_miles', ascending=False)
)
mileage_leaderboard['avg_miles_per_ride'] = (
    mileage_leaderboard['total_miles'] / mileage_leaderboard['rides_attended']
)

mileage_leaderboard

        rider  total_miles  rides_attended  avg_miles_per_ride
2        Anna          876              37           23.675676
3       Apple          656              29           22.620690
0      Alex A          638              24           26.583333
6     Ben Lin          572              29           19.724138
17       Josh          544              22           24.727273
28      Wenbo          465              20           23.250000
12    David M          412              17           24.235294
11    David K          355              17           20.882353
14      Hardy          260               7           37.142857
23      Sarah          240              11           21.818182
16    Jarrett          231               7           33.000000
9   Constance          225               8           28.125000
1    Andrew K          220               8           27.500000
15      Ilana          220              11           20.000000
5     Ben Law          220               8           27.500000
4       Ben D          202               6           33.666667
19      Katie          199              10           19.900000
22   Rachel V          192              10           19.200000
24       Sten          179               9           19.888889
7   Christian          176               7           25.142857
21       Nick          171               9           19.000000
27    Wanying          166               8           20.750000
26    Vignesh          157               8           19.625000
20      Milla          144               8           18.000000
13       Emma          127               6           21.166667
25        Tim          108               6           18.000000
8       Conor          101               6           16.833333
18       Kate           95               5           19.000000
10     Cooper           94               5           18.800000

In [160]:
def longest_streak(dates):
    dates = sorted(dates)
    if not dates: return 0

    streak = 1
    max_streak = 1

    for i in range(1, len(dates)):
        # 7 Dyas for weekly rides
        if (dates[i] - dates[i-1]).days == 7: streak += 1
        else: streak = 1
        max_streak = max(max_streak, streak)
    return max_streak

streak_df = (
    attendance_df.groupby("rider")["date"]
    .apply(lambda d: longest_streak(list(d)))
    .reset_index(name="longest_streak")
)
streak_df = streak_df[streak_df["rider"].isin(regular_riders)]
streak_df.sort_values("longest_streak", ascending=False, inplace=True)
streak_df = streak_df[streak_df["longest_streak"] > 1]

In [162]:
def longest_hiatus_rides(rider_dates, all_ride_dates):
    rider_dates = sorted(rider_dates)
    all_ride_dates = sorted(all_ride_dates)
    
    if len(rider_dates) < 2: return 0

    rider_indices = [all_ride_dates.index(d) for d in rider_dates]
    # Gap in ride
    gaps = [rider_indices[i] - rider_indices[i-1] - 1 for i in range(1, len(rider_indices))]

    return max(gaps)

all_ride_dates = sorted(rides_df["date"].unique())
hiatus_df = (
    attendance_df.groupby("rider")["date"]
    .apply(lambda d: longest_hiatus_rides(list(d), all_ride_dates))
    .reset_index(name="longest_hiatus_rides")
)

hiatus_df = hiatus_df[hiatus_df["rider"].isin(regular_riders)]
hiatus_df.sort_values("longest_hiatus_rides", ascending=False, inplace=True)
hiatus_df = hiatus_df[hiatus_df["longest_hiatus_rides"] > 2]

# Plotting Charts

In [163]:
import plotly.io as pio
from plotly.colors import qualitative

# Define the template
wrapped_template = go.layout.Template(
    layout=dict(
        title=dict(
            x=0.5
        ),

        width=450,
        height=800,
        margin=dict(l=80, r=10, t=50, b=50),

        colorway=qualitative.Set3
    )
)
pio.templates["wrapped"] = wrapped_template
px.defaults.template = "wrapped"
wrapped_template.layout.font = dict(size=16)
wrapped_template.layout.title.font = dict(size=22)
px.defaults.color_discrete_sequence = qualitative.Set3

In [164]:
attendance_regular

         rider  count  rank
14        Anna     37     1
15       Apple     29     2
20     Ben Lin     29     3
3       Alex A     24     4
57        Josh     22     5
107      Wenbo     20     6
30     David K     17     7
31     David M     17     8
46       Ilana     11     9
93       Sarah     11    10
62       Katie     10    11
86    Rachel V     10    12
82        Nick      9    13
96        Sten      9    14
11    Andrew K      8    15
19     Ben Law      8    16
28   Constance      8    17
79       Milla      8    18
103    Vignesh      8    19
106    Wanying      8    20
26   Christian      7    21
44       Hardy      7    22
49     Jarrett      7    23
18       Ben D      6    24
27       Conor      6    25
37        Emma      6    26
100        Tim      6    27
29      Cooper      5    28
60        Kate      5    29

In [166]:
fig_top_riders = px.bar(
    attendance_regular,
    y="rider",
    x="count",
    title="Rider Attendance Leaderboard",
    text_auto=True
)

fig_top_riders.update_layout(
    yaxis=dict(
        categoryorder="array",
        categoryarray=attendance_regular["rider"]
    )
)

fig_top_riders.show()

In [177]:
fig_top_riders = px.bar(
    attendance_regular, 
    y="rider", x="count",
    title="Rider Attendance Leaderboard", 
    text_auto=True)
fig_top_riders.update_traces(
    textposition="inside",
    textangle=0
)
fig_top_riders.update_layout(
    title_x=0.5,
    width=600,
    height=800,
    yaxis=dict(
        title=None,
        categoryorder='array',
        categoryarray=attendance_regular["rider"]
    ),
    xaxis_title='Number of Rides',
    barmode='stack',
)
fig_top_riders.update_yaxes(autorange="reversed")
fig_top_riders.show()
fig_top_riders.write_image(f'{year}/rider_leaderboard_{year}.png', format='png')
# fig_top_riders.write_html(f"{year}/rider_leaderboard_{year}.html")

In [ ]:
fig_top_riders_landscape = px.bar(
    attendance_regular, 
    y="rider",
    x="count",
    title="TBD 2025 Attendance Leaderboard",
    text_auto=True,
)

fig_top_riders_landscape.update_traces(
    marker_color="#EA4630",   # Christmas red
    marker_line_width=2,
    marker_line_color="white",
    textposition="outside"
)

fig_top_riders_landscape.update_layout(
    title_x=0.5,
    width=1280,
    height=720,
    margin=dict(l=5, r=5, t=50, b=5),
    yaxis=dict(title=None, categoryorder="total ascending"),
    xaxis_title="Number of Rides",
    template="plotly_white"
)

fig_top_riders_landscape.show()
fig_top_riders_landscape.write_image(f'{year}/landscape_rider_leaderboard_{year}.png', format='png')
# fig_top_riders.write_html(f"{year}/rider_leaderboard_{year}.html")

In [ ]:
top10 = mileage_leaderboard.nlargest(11, 'total_miles')

fig_mileage_leaderboard = px.scatter(
    top10,
    x='rides_attended',
    y='total_miles',
    text='rider',
    title='Top Riders by Mileage: Miles vs Rides Attended',
    labels={
        'rides_attended': 'Rides Attended',
        'total_miles': 'Total Miles'
    }
)

fig_mileage_leaderboard.update_layout(
    title_x=0.5,
    width=450,
    height=800,
)
fig_mileage_leaderboard.update_traces(
    textposition='middle center',
    marker=dict(size=20)
)
fig_mileage_leaderboard.show()

In [174]:


fig_mileage_leaderboard = px.bar(
    mileage_leaderboard,
    x='total_miles',
    y='rider',
    orientation='h',
    text='total_miles',
    title='Top Riders by Total Miles (2025)',
    labels={
        'total_miles': 'Total Miles',
        'name': 'Rider'
    }
)

fig_mileage_leaderboard.update_traces(
    texttemplate='%{text:.0f}',
    textposition='inside'
)

fig_mileage_leaderboard.update_layout(
    yaxis=dict(
        title=None,
        categoryorder='total ascending'
    ),
    title_x=0.5,
    width=600,
    height=800,
)

fig_mileage_leaderboard.show()
fig_mileage_leaderboard.write_image(f"{year}/top_mileage_{year}.png", format="png")

In [178]:
fig_streak = px.bar(
    streak_df,
    y="rider",
    x="longest_streak",
    title="Longest Attendance Streak per Rider",
    text_auto=True
)
fig_streak.update_traces(
    textposition="inside",
    textangle=0
)
fig_streak.update_layout(
    title_x=0.5,
    width=600,
    height=800,
    yaxis=dict(title=None, categoryorder='total ascending'),
    xaxis_title='Number of Rides',
    barmode='stack',
)
fig_streak.show()
fig_streak.write_image(f"{year}/attendance_streaks_{year}.png", format="png")
# fig_streak.write_html(f"{year}/attendance_streaks_{year}.html")

In [ ]:

fig_hiatus = px.bar(
    hiatus_df,
    y="rider",
    x="longest_hiatus_rides",
    title="Longest Hiatus Before Comeback",
    text_auto=True
)
fig_hiatus.update_traces(
    textposition="outside"
)
fig_hiatus.update_layout(
    title_x=0.5,
    width=600,
    height=800,
    yaxis=dict(title=None, categoryorder='total ascending'),
    xaxis_title='Number of Rides',
    barmode='stack',
)
fig_hiatus.show()
fig_hiatus.write_image(f"{year}/hiatus_comeback_{year}.png", format="png")
# fig_hiatus.write_html(f"{year}/hiatus_comeback_{year}.html")

## Coffee Shops Sunburst

In [ ]:
import plotly.colors as pc
colors = pc.qualitative.Set3  # or any palette
fig_start_sunburst = px.sunburst(
    rides_df, 
    path=["start", "route", "full_route"],
    color_discrete_sequence=colors,
    color="start",
    title="Ride Routes and Trails"
)
fig_start_sunburst.update_traces(
    marker=dict(line=dict(color="black", width=1)),  # stronger black borders
)
fig_start_sunburst.update_layout(
    title_x=0.5,
    title_font_size=22,
    width=300,
    height=300,
    margin=dict(l=5, r=5, t=100, b=5),  # left, right, top, bottom margins
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)',
)
# fig_start_sunburst.update_traces(textinfo='label')
fig_start_sunburst.show()
fig_start_sunburst.write_image(f'{year}/start_sunburst_{year}.png', format='png', scale=2)
# fig_start_sunburst.write_html(f'{year}/start_sunburst_{year}.html')

In [ ]:
import plotly.colors as pc
colors = pc.qualitative.Set2  # or any palette
fig_sunburst = px.sunburst(
    rides_df,
    path=["route", "coffee_shop"],
    color_discrete_sequence=colors,
    title="Coffee Shop by Route"
)
fig_sunburst.update_traces(
    marker=dict(line=dict(color="black", width=1))  # stronger black borders
)
fig_sunburst.update_layout(
    title_x=0.5,
    title_font_size=22,
    width=300,
    height=300,
    margin=dict(l=5, r=5, t=100, b=5),  # left, right, top, bottom margins
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)',
)
# fig_sunburst.update_traces(textinfo='label')
fig_sunburst.show()
fig_sunburst.write_image(f'{year}/coffee_sunburst_{year}.png', format='png', scale=2)
# fig_sunburst.write_html(f'{year}/coffee_sunburst_{year}.html')

In [ ]:
fig_sunburst = px.sunburst(rides_df, path=["route", "full_route", "coffee_shop"],)
fig_sunburst.update_layout(
    width=450,
    height=800,
    margin=dict(l=5, r=5, t=100, b=5),  # left, right, top, bottom margins
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)',
)
fig_sunburst.show()
fig_sunburst.write_image(f'{year}/ride_sunburst_{year}.png', format='png')
fig_sunburst.write_html(f'{year}/ride_sunburst_{year}.html')

## Ride sizes
Plot for total attendance at rides over time. Includes 4 week rolling average.

In [181]:
official_rides = rides_df[rides_df["official_ride"] == True]
official_dates = official_rides["date"].unique()
attendance_official = attendance_df[attendance_df["date"].isin(official_dates)]
attendance_counts = attendance_official.groupby("date")["rider"].nunique().reset_index()
attendance_counts = attendance_counts.sort_values("date")
attendance_counts.columns = ['date', 'attendance']

# Rolling average (4 weeks)
attendance_counts["rolling_avg"] = attendance_counts["attendance"].rolling(4, min_periods=1).mean()

In [182]:
attendance_counts

         date  attendance  rolling_avg
0  2025-01-04          10    10.000000
1  2025-01-18           8     9.000000
2  2025-02-01          14    10.666667
3  2025-02-15           6     9.500000
4  2025-02-22           8     9.000000
5  2025-03-01           8     9.000000
6  2025-03-08           9     7.750000
7  2025-03-15          14     9.750000
8  2025-03-22          12    10.750000
9  2025-03-29          14    12.250000
10 2025-04-05          10    12.500000
11 2025-04-12          10    11.500000
12 2025-04-19          10    11.000000
13 2025-04-25          10    10.000000
14 2025-05-03           8     9.500000
15 2025-05-10           9     9.250000
16 2025-05-17          11     9.500000
17 2025-05-24          13    10.250000
18 2025-05-31          10    10.750000
19 2025-06-07          14    12.000000
20 2025-06-21           7    11.000000
21 2025-06-28          21    13.000000
22 2025-07-05           8    12.500000
23 2025-07-12          19    13.750000
24 2025-07-19          11    14.750000
25 2025-07-26          21    14.750000
26 2025-08-02          19    17.500000
27 2025-08-16          22    18.250000
28 2025-08-23          16    19.500000
29 2025-09-06          11    17.000000
30 2025-09-13          16    16.250000
31 2025-09-20          10    13.250000
32 2025-09-27           9    11.500000
33 2025-10-04          12    11.750000
34 2025-10-11          11    10.500000
35 2025-10-18           9    10.250000
36 2025-10-25          14    11.500000
37 2025-11-01           6    10.000000
38 2025-11-02          10     9.750000
39 2025-11-08          11    10.250000
40 2025-12-06           6     8.250000
41 2025-12-20           6     8.250000

In [183]:
rides_df["date"] = pd.to_datetime(rides_df["date"]).dt.normalize()
attendance_df["date"] = pd.to_datetime(attendance_df["date"]).dt.normalize()

In [184]:
fig_attendance = px.line(
    attendance_counts, x="date", y="attendance", 
    markers=True, 
    title=f"TBD {year} Ride Attendance",
    # line_shape='spline'
)
fig_attendance.update_xaxes(
    fixedrange=False,
    dtick="M1",
    tickformat="%b",
    range=[pd.to_datetime(f'{year}-01-01'),pd.to_datetime(f'{year}-12-31')],
    gridcolor='silver'
)
fig_attendance.update_layout(
    title_x=0.5,
    width=800,
    height=400,
    margin=dict(l=5, r=5, t=50, b=5),  # left, right, top, bottom margins
    yaxis=dict(title=None),
    yaxis_title='Number of Riders',
    plot_bgcolor='#fffcf7',
    paper_bgcolor='#fffcf7',
    # template='simple_white',
)
fig_attendance.update_traces(
    connectgaps=True, 
    line=dict(width=5),
)
# fig_attendance.show()
# fig_attendance.write_html(f"{year}/attendance.html")

In [185]:
fig_attendance.update_layout(
    title_x=0.5,
    width=450,
    height=800,
    margin=dict(l=5, r=5, t=50, b=5),  # left, right, top, bottom margins
    yaxis=dict(title=None),
    yaxis_title='Number of Riders',
    plot_bgcolor='#fffcf7',
    paper_bgcolor='#fffcf7',
    # template='simple_white',
)
fig_attendance.update_traces(
    connectgaps=True, 
    line=dict(width=5),
)
fig_attendance.show()
# fig.write_image(f'{year}/{year}_attendance.png', format='png')

In [190]:
fig_rolling_avg = go.Figure()

# Scatter points for attendance
fig_rolling_avg.add_trace(go.Scatter(
    x=attendance_counts["date"],
    y=attendance_counts["attendance"],
    mode="markers",
    name="Attendance",
    marker=dict(
        size=12,
        # color="#146B3A",      # Christmas green
        line=dict(width=1, color="white")
    ),
    opacity=0.85
))
# Connected points for rolling average
fig_rolling_avg.add_trace(go.Scatter(
    x=attendance_counts["date"],
    y=attendance_counts["rolling_avg"],
    mode="lines",
    name="4-Ride Rolling Avg",
    line=dict(
        width=4,
        # color="#EA4630"       # Christmas red
    )
))
fig_rolling_avg.update_layout(
    title_x=0.5,
    title=f"{year} Ride Attendance (4-Ride Rolling Average)",
    width=1280,
    height=720,
    margin=dict(l=5, r=5, t=80, b=5),  # left, right, top, bottom margins
    yaxis=dict(title=None),
    showlegend=False,
    yaxis_title='Number of Riders',
    plot_bgcolor='#fffcf7',
    paper_bgcolor='#fffcf7',
    font=dict(size=20),
    title_font_size=34,
)
# fig_rolling_avg.show()
# fig_rolling_avg.write_html(f"{year}/landscape_attendance_with_rolling_avg_{year}.html")
# fig_rolling_avg.write_image(f'{year}/landscape_attendance_with_rolling_avg__{year}.png', format='png')

In [250]:
fig_rolling_avg.update_layout(
    width=450,
    height=600,
    margin=dict(l=5, r=5, t=50, b=5),  # left, right, top, bottom margins
    yaxis=dict(title=None),
    plot_bgcolor='white',
    paper_bgcolor='white',
    showlegend=False, 
    font=dict(size=14),
    title_font_size=18,
)
fig_rolling_avg.show()

fig_rolling_avg.write_image(f'{year}/attendance_with_rolling_avg_{year}.png', format='png')

In [206]:
import plotly.graph_objects as go

fig = go.Figure()

# Initial traces (first point)
fig.add_trace(go.Scatter(
    x=attendance_counts["date"][:1],
    y=attendance_counts["attendance"][:1],
    mode="markers",
    marker=dict(size=12, line=dict(width=1, color="white")),
    opacity=0.85,
    name="Attendance"
))

fig.add_trace(go.Scatter(
    x=attendance_counts["date"][:1],
    y=attendance_counts["rolling_avg"][:1],
    mode="lines",
    line=dict(width=4),
    name="4-Ride Rolling Avg"
))

# Create frames
frames = []
for i in range(1, len(attendance_counts)):
    frames.append(go.Frame(
        data=[
            go.Scatter(
                x=attendance_counts["date"][:i+1],
                y=attendance_counts["attendance"][:i+1],
                mode="markers"
            ),
            go.Scatter(
                x=attendance_counts["date"][:i+1],
                y=attendance_counts["rolling_avg"][:i+1],
                mode="lines"
            )
        ],
        name=str(i)
    ))

fig.frames = frames

In [242]:
# Compute global ranges
x_range = [
    pd.Timestamp(f"{year}-01-01"),
    pd.Timestamp(f"{year}-12-31")
]

y_min = min(
    attendance_counts["attendance"].min(),
    attendance_counts["rolling_avg"].min()
)
y_max = max(
    attendance_counts["attendance"].max(),
    attendance_counts["rolling_avg"].max()
)

# Add padding so markers never clip
pad = (y_max - y_min) * 0.15
y_range = [5, 23]


fig.update_layout(
    width=450,
    height=600,
    margin=dict(l=20, r=20, t=60, b=60),  # important!
    plot_bgcolor="white",
    paper_bgcolor="white",
    showlegend=False,
    font=dict(size=14),
    title_font_size=18,
    title=f"{year} Ride Attendance<br><sup>(4-Ride Rolling Average)</sup>",
    title_x=0.5,
    xaxis=dict(
        type="date",
        range=x_range,
        fixedrange=True,
        automargin=True,
        tickangle=45,
        tickformat="%b",
        dtick="M1"
    ),
    yaxis=dict(
        range=y_range,
        fixedrange=True,
        automargin=True,
        showgrid=True,
        gridcolor="rgba(0,0,0,0.1)",  # very light gray
        gridwidth=0.5,
        griddash="dot",
        zeroline=False,
        dtick=2
    ),
    updatemenus=[{
        "type": "buttons",
        "buttons": [{
            "label": "Play",
            "method": "animate",
            "args": [None, {"frame": {"duration": 150, "redraw": True},
                            "fromcurrent": True}]
        }]
    }]
)

fig.show()

In [241]:
import os

os.makedirs("frames", exist_ok=True)

for i in range(1, len(attendance_counts) + 1):
    fig = go.Figure()

    # Scatter points
    fig.add_trace(go.Scatter(
        x=attendance_counts["date"][:i],
        y=attendance_counts["attendance"][:i],
        mode="markers",
        marker=dict(size=12, line=dict(width=1, color="white")),
        opacity=0.85
    ))


    fig.add_trace(go.Scatter(
        x=attendance_counts["date"][:i],
        y=attendance_counts["rolling_avg"][:i],
        mode="lines",
        line=dict(width=4)
    ))

    # Apply locked layout
    fig.update_layout(
        width=450,
        height=600,
        margin=dict(l=20, r=20, t=60, b=60),  # important!
        plot_bgcolor="white",
        paper_bgcolor="white",
        showlegend=False,
        font=dict(size=14),
        title_font_size=18,
        title=f"{year} Ride Attendance<br><sup>(4-Ride Rolling Average)</sup>",
        title_x=0.5,
        xaxis=dict(
            type="date",
            range=x_range,
            fixedrange=True,
            automargin=True,
            tickangle=45,
            tickformat="%b",
            dtick="M1"
        ),
        yaxis=dict(
            range=y_range,
            fixedrange=True,
            automargin=True,
            showgrid=True,
            gridcolor="rgba(0,0,0,0.1)",  # very light gray
            gridwidth=0.5,
            griddash="dot",
            zeroline=False,
            dtick=2
        ),
    )

    fig.write_image(f"{year}/frames/frame_{i:03d}.png")

In [249]:
# Source - https://stackoverflow.com/a
# Posted by Dave Babbitt, modified by community. See post 'Timeline' for change history
# Retrieved 2025-12-30, License - CC BY-SA 4.0

import os
import imageio

png_dir = f"{year}/frames/"
images = []
durations = [] 
for file_name in sorted(os.listdir(png_dir)):
    if file_name.endswith('.png'):
        file_path = os.path.join(png_dir, file_name)
        images.append(imageio.imread(file_path))
        durations.append(0.1)

# Make it pause at the end so that the viewers can ponder
images.append(imageio.imread(os.path.join(png_dir, "frame_042.png")))
durations.append(1.0)

imageio.mimsave(f"{year}/animation.gif", images, duration=durations, loop=1)

/var/folders/6s/2lcz4zcx0515kv6t7ks2qj0h0000gn/T/ipykernel_2233/2880490586.py:14: DeprecationWarning:

Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.

/var/folders/6s/2lcz4zcx0515kv6t7ks2qj0h0000gn/T/ipykernel_2233/2880490586.py:18: DeprecationWarning:

Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.

## Most popular ride by rider count

In [ ]:

christmas_classic = [
    "#EA4630",  # bright red
    "#146B3A",  # green
    "#F8B229",  # gold
    "#BB2528",  # deep red
    "#165B33",  # dark green
    "#D9D9D9",  # silver
]

route_counts = (
    rides_df.groupby("route")["num_riders"]
    .sum()
    .reset_index()
    .sort_values("num_riders", ascending=False)
)

fig_routes_pie = px.pie(
    route_counts,
    names="route",
    values="num_riders",
    title="Route Popularity<br>(Total Riders)",
    color_discrete_sequence=christmas_classic,
)

fig_routes_pie.update_traces(
    textposition="inside",
    textinfo="value+label",
    textfont=dict(size=8),
    marker=dict(
        line=dict(color="white", width=1)
    ),
)

fig_routes_pie.update_layout(
    width=300,
    height=300,
    margin=dict(l=10, r=10, t=100, b=10),
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    font=dict(size=18),
    title_x=0.5,
    title_font_size=22,
    showlegend=False,
    legend=dict(
        orientation="h",
        y=-0.05,
        x=0.5,
        xanchor="center"
    )
)

fig_routes_pie.show()

fig_routes_pie.write_image(
    f"{year}/route_popularity_pie_{year}.png",
    format="png",
    scale=2   # CRITICAL for PowerPoint sharpness
)


# fig_routes_pie.write_image(f"{year}/route_popularity_pie_{year}.png", format='png')
fig_routes_pie.write_html(
    f"{year}/route_popularity_pie_{year}.html", 
    include_plotlyjs=False,
    full_html=False
)

## Numerical Stats

In [ ]:
# Total person-miles
rides_df["person_miles"] = rides_df["num_riders"] * rides_df["miles"]
total_miles = rides_df["person_miles"].sum()

# Median miles
median_rides = rides_df["miles"].median()

# Total official rides
official_rides = rides_df[rides_df["official_ride"]==True].shape[0]

# Total number of rides
total_rides = rides_df.shape[0]

# Total number of riders
total_riders = attendance_df["rider"].shape[0]

# Total unique riders
unique_riders = attendance_df["rider"].nunique()

# Riders who appeared only once
one_time_riders_count = (attendance_df.groupby("rider")["date"].nunique() == 1).sum()

# Mean attendance per ride
avg_attendance = attendance_df.groupby("date")["rider"].nunique().mean()

# Median attendance per ride
med_attendance = attendance_df.groupby("date")["rider"].nunique().median()

# Largest single-ride attendance
largest_attendance = rides_df["num_riders"].max()

# Print summary
print(f"Total person-miles ridden: {total_miles}")
print(f"Median ride length: {median_rides}")
print(f"Official rides: {official_rides}")
print(f"Total rides: {total_rides}")
print(f"Total riders: {total_riders}")
print(f"Total unique riders: {unique_riders}")
print(f"Riders who only appeared once: {one_time_riders_count}")
print(f"Average attendance per ride: {avg_attendance:.2f}")
print(f"Median attendance per ride: {med_attendance:.2f}")
print(f"Largest single-ride attendance: {largest_attendance}")

Total person-miles ridden: 11523
Median ride length: 20.0
Official rides: 41
Total rides: 44
Total riders: 498
Total unique riders: 122
Riders who only appeared once: 63
Average attendance per ride: 11.07
Median attendance per ride: 10.00
Largest single-ride attendance: 22

## Long script

In [ ]:
rides_df

,date,official_ride,start,route,full_route,coffee_shop,num_riders,miles,selfie,person_miles
0,2025-01-04,True,CCT Trailhead,WOD,MVT-WOD,Rare Bird,10,18,True,180
1,2025-01-18,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,8,20,True,160
2,2025-02-01,True,CCT Trailhead,CCT-RCP,CCT-RCP,Olivia's Kitchen,14,20,True,280
3,2025-02-15,True,Gravelley Point,Alexandria,MVT-Crystal City,Swing's,6,19,True,114
4,2025-02-22,True,Navy Yard,ART-MBT,ART-MBT,Vigilante,8,16,True,128
5,2025-03-01,True,Gravelley Point,WOD,MVT-WOD,Rare Bird,8,18,True,144
6,2025-03-08,True,Gravelley Point,Alexandria,MVT-Crystal City,Hypergoat,9,16,True,144
7,2025-03-15,True,Navy Yard,ART-MBT,ART-MBT,Vigilante,14,19,True,266
8,2025-03-22,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,12,20,True,240
9,2025-03-29,True,Gateway Park,WOD,Military-WOD,Coffee Republic,14,28,True,392
10,2025-04-05,True,Gravelley Point,Alexandria,MVT-Crystal City,Misha's,10,17,True,170
11,2025-04-12,True,Gateway Park,WOD,MVT-WOD,Frames,10,33,True,330
12,2025-04-19,True,Navy Yard,ART-MBT,ART-MBT,Vigilante,10,16,True,160
13,2025-04-25,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,10,20,True,200
14,2025-05-03,True,Gravelley Point,Alexandria,MVT-Crystal City,Swing's,8,19,True,152
15,2025-05-10,True,Gateway Park,WOD,Military-WOD-MVT,Rare Bird,9,25,True,225
16,2025-05-17,True,Navy Yard,ART-MBT,ART-MBT,Mt Rainier Farmers Market,11,16,True,176
17,2025-05-24,True,Gravelley Point,WOD,MVT-WOD,Monk's,13,97,True,1261
18,2025-05-31,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,10,20,True,200
19,2025-06-07,True,Navy Yard,Alexandria,Oxon Hill-Crystal City,Misha's,14,18,True,252
20,2025-06-21,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,7,20,True,140
21,2025-06-28,True,Dupont Circle,RCP-MBT,RCP-MBT,Donut Run,21,16,True,336
22,2025-07-05,True,Navy Yard,ART-MBT,ART-MBT,Vigilante,8,16,True,128
23,2025-07-12,True,Dupont Circle,Alexandria,MVT-Crystal City,Hypergoat,19,15,True,285
24,2025-07-19,True,Gateway Park,WOD,Military-WOD,Frames,11,28,True,308
25,2025-07-26,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,21,20,True,420
26,2025-08-02,True,Navy Yard,ART-MBT,ART-Sligo-MBT,Vigilante,18,33,True,594
27,2025-08-09,False,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,2,20,True,40
28,2025-08-16,True,Arlington Cemetery,WOD,MVT-WOD,Rare Bird,22,20,True,440
29,2025-08-23,True,Gravelley Point,Alexandria,MVT-Crystal City,Swing's,16,19,True,304
30,2025-08-30,False,Gateway Park,WOD,MVT-WOD,Weenie Beenie,8,33,True,264
31,2025-09-06,True,CCT Trailhead,CCT-RCP,CCT-RCP,Bethesda Bagel,11,20,True,220
32,2025-09-13,True,Navy Yard,Alexandria,Oxon Hill-Crystal City,Swing's,16,18,True,288
33,2025-09-20,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,10,20,True,200
34,2025-09-27,True,Grace Street Coffee,ART-MBT,RCP-Sligo-ART,Vigilante,9,33,True,297
35,2025-10-04,True,Gravelley Point,Alexandria,MVT-Crystal City,Buzz Bakeshop,12,19,True,228
36,2025-10-11,True,Gateway Park,WOD,Military-WOD,Frames,11,28,True,308
37,2025-10-18,True,Gateway Park,Alexandria,MVT-Crystal City,Hypergoat,9,19,True,171
38,2025-10-25,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,14,20,True,280
39,2025-11-01,True,CCT Trailhead,CCT-RCP,CCT-RCP,Coffefi,6,20,True,120
40,2025-11-02,True,Gravelley Point,NOVA Loop,NOVA Loop,Myung Ga Kimbap,10,55,True,550
41,2025-11-08,True,CCT Trailhead,CCT-RCP,CCT-RCP,Ceremony,11,20,True,220
42,2025-11-15,False,CCT Trailhead,CCT-RCP,CCT-RCP,Grace Street Coffee,5,20,True,100
43,2025-12-06,True,Navy Yard,Alexandria,Oxon Hill-Crystal City,St. Elmo's,6,18,True,108